Examples
alejobh/hooks-advanced-talk pull request #4
Opened 2020-09-29 17:49 UTC by alejobh

## Summary

* Added `useEffect` example
* Added `useEffect` example

## Screenshots

[Change!] Show the screenshots of the views you modified.

## Trello Card

[Change!] Link to the associated Trello card.

2020-09-29 19:01 UTC, pabloferro commented on src/app/screens/Dashboard/screens/ReactQueryExample/components/Movies/components/MoviesCache/index.tsx
> +  const movies: GhibliMovieI[] | undefined = cache.getQueryData(['movies', limit]);
Tiene sentido usar el cache directamente? O es para mostrar?

2020-09-29 19:37 UTC, pabloferro requested changes

2020-09-29 19:37 UTC, pabloferro commented on src/app/screens/Dashboard/screens/TodoList/components/NewTodo/index.tsx
> +import { actionCreators } from '~contexts/TodosContext/reducer';
I'd move this context to the screens/TodoList folder.

2020-09-29 19:37 UTC, pabloferro commented on src/app/screens/Dashboard/screens/TodoList/components/Todos/components/Todo/index.tsx
> +function Todo({ todo }: Props) {
I'd name this `TodoItem` and the interface `Todo` o `TodoTask`, what do you think?

2020-09-29 19:37 UTC, pabloferro commented on src/app/screens/Dashboard/screens/UseLayoutEffect/index.tsx
> +// eslint-disable-next-line no-magic-numbers
I'd disable this rule for the entire project 😅

2020-09-29 19:37 UTC, pabloferro commented on src/app/screens/Dashboard/screens/UseLayoutEffect/index.tsx
> +  }, [value1, value2]);
Why is value2 here?

2020-09-29 19:37 UTC, pabloferro commented on src/app/screens/Dashboard/screens/UseRequestExample/index.tsx
> +  // Comment this useEffect, and put limit on dependencies arraay on useMoviesUseRequest (useRequest) to see magic
```suggestion
  // Comment this useEffect, and put limit on dependencies array on useMoviesUseRequest (useRequest) to see magic
```

2020-09-29 21:12 UTC, alejobh commented on src/app/screens/Dashboard/screens/ReactQueryExample/components/Movies/components/MoviesCache/index.tsx
> +  const movies: GhibliMovieI[] | undefined = cache.getQueryData(['movies', limit]);
Es para mostrar, y se usa directamente

2020-09-29 21:19 UTC, alejobh commented on src/app/screens/Dashboard/screens/UseLayoutEffect/index.tsx
> +  }, [value1, value2]);
:harold:

2020-09-30 13:32 UTC, pabloferro approved these changes

2020-09-30 19:43 UTC, merged